name: 'Create Tag Action'
description: 'Create Git tag on repository'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  tag:
    description: 'Tag to create.'
    required: true
  message:
    description: 'Message for the tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure git
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Create Tag Action"
        git config --global --add safe.directory /github/workspace

    - name: Create and push tag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating tag ${{ inputs.tag }} with message '${{ inputs.message }}' as '${{ github.actor }}'"
        git fetch origin --tags --quiet
        git tag -a "${{ inputs.tag }}" -m "${{ inputs.message }}" "${{ github.sha }}" -f
        git push --tags -f
